import numpy as np


# dont use LdaMallet objects as inputs in case they dont want to use gensim
def rel_ent_key_list(doc_topic_matrix: ndarray, n: int):
    # a list of the top n keywords generated by relative entropy
    pass
